### ISSUE TITLE
IDS support in IfcOpenShell

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1349]
https://github.com/IfcOpenShell/IfcOpenShell/commit/4e889b75d788def4d7209dc75d163e9bb02cb36e implements a very basic BIMTester integration. Ping @aothms as well as @rbertucat who this might impact, if IfcRail is testing pset applicability too.

To run, just point to the IDS XML instead of a feature file.

```
$ bimtester -f ids01.xml -i Duplex_A_20110505.ifc -r report.html
```

HTML report looks like this:

![2021-02-28-144158_1920x1080_scrot](https://user-images.githubusercontent.com/88302/109407229-245bfa00-79d3-11eb-986f-2adf5ffc72f1.png)

Because it just uses the same argument to specify a feature file, this means that the Blender UI to BIMTester, the FreeCAD UI to BIMTester, as well as the standalone UIs to BIMTester built by @berndhahnebach and @rbertucat all can just work out of the box.

![2021-02-28-150528_692x139_scrot](https://user-images.githubusercontent.com/88302/109407617-6a668d00-79d6-11eb-8c2d-a2b4fb47134f.png)

I really like this new IDS approach. I can read the XML and it just makes sense.

BIMTester can provide additional value on top of this IDS XML spec by providing a test running interface, as well as a HTML report generator, and an xUnit compatible output (therefore, will integrated into many continuous integration apps).

As a separate concept to test running, there is the whole Gherkin approach. The biggest benefit of Gherkin is the ability for humans to understand it, and that it can be included in contracts, and read by non-technical people. At the end of the day, it still needs code to check. Right now, this is the biggest disadvantage of BIMTester. If you want to write your own check, you need to know a bit of Python + the IfcOpenShell API. I see this IDS XML as replacing the Python coding for simple checks that anybody can write who doesn't need / want to know Python or the IfcOpenShell API. And whilst IDS XML is great for general and common specifications, it will never cover everything, so allowing both approaches is great.

Possible Gherkin sentences:

```
 * IFC data must comply with the IDS provided in "ids01.xml"
```

... this is easy, but doesn't communicate well to non-technical people - defeats the purpose of Gherkin. Maybe it should exist as a template simply for techies who are prototyping new bSI standards, but definitely deserves the blank looks it'll encounter on real projects :)

```
 * All entities belonging to "IfcSpace" must have a property set called "PSet_Revit_Identity Data" with a "Name" property filled with one of the following values:
    | Living Room |
    | Kitchen     |
```

... this can autoconvert XML<->Gherkin, and is highly specific. Kinda midway - readable but contains jargon for non-techies, and extra effort for techies, since it'll probably end up being its own DSL and would need to be translated into different languages ...

```
 * All spaces must be either a living room or kitchen.
```

... this is perhaps the best from a Gherkin point of view. This looks like exactly the type of sentence that already exists in contracts. From a UX perspective, there can be a simple UI that a spec writer can use to link this arbitrary user sentence to an XML definition. Easy for the manager, easy for the spec writer (can use any tool, IfcOpenShell Python API optional). I personally think this would be the way to go.

**Comment by Moult** [comment]
A couple of minor implementation comments - one of the really valuable things about the way most BIMTester checks are implemented is that it doesn't just say "this failed" or "this passed". It formats it in this way:

```
 1. We expect foo to be bar. <-- this is the exchange requirement we want. This should always read exactly the same thing.
(Note: if foo is bar, then we move on. No details are shown. Otherwise... read on...)
The element 3621=IfcSpace('2gRXFgjRn2HPE$YoDLX3FC',#33,'B205','',$,#3611,#3620,'Utility',.ELEMENT.,.INTERNAL.,$) has a property foo with the value "baz" instead of "bar".
```

This way:

 1. There is a consistent, unchanged sentence that clearly explains the expected exchange requirement (right now, the screenshot in the previous comment has a changing sentence, which can create confusion)
 2. Only if there is an error, is complex technical stuff shown (i.e. the STEP code). The concept is that managers are interested in green, whereas techies are interested in red.
 3. The error should not just say "failed", it should give useful information like "it was baz, not bar". This really, really helps with users debugging.

**Comment by aothms** [comment]
@Moult very cool! I formatted the messages, feel free to adapt to your wishes. The logger verbosity indicates error or success so you don't need to test the string content.

~~~
Given an instance with an entity name 'IfcSpace'
We expect a property 'Name' in 'PSet_Revit_Identity Data' with value 'Living Room or Kitchen'
#349=IfcSpace('0pNy6pOyf7JPmXRLgxs3sW',#1,'R301','',$,#17700,#16934,'Roof',.ELEMENT.,.INTERNAL.,$) has a property 'Name' in 'PSet_Revit_Identity Data' with value 'Roof' so is not compliant
~~~

'Living Room or Kitchen' should be 'Living Room' or 'Kitchen' ideally, but that's a bit of work that I'd like to postpone.

**Comment by Moult** [comment]
By the way, I think there would be value in building a UI to generate the IDS XML as not everybody can write XML - this can also help test out the usability and full workflow for the average BIM user. Happy to do this, but probably need some guidance on the rules (e.g. an XSD, or an explanation of what it allows).

**Comment by aothms** [comment]
Good point. The xsd is still in progress at bSI. That's when things get
precise. So I don't think it'll be ready in a short time frame

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op ma 1 mrt. 2021 09:24 schreef Dion Moult <notifications@github.com>:

**Comment by berndhahnebach** [comment]
guys, thats great stuff :)

**Comment by Moult** [comment]
@berndhahnebach https://github.com/buildingSMART/IDS/blob/master/Development/First%20production%20release/Examples.md

Ping @aothms and @berlotti - I will potentially be digging into the guts of the new FM Handover View MVDs as well as the spreadsheetML conversions. I think this makes for an excellent usecase for writing an IDS that checks whether or not all the appropriate fields are filled out. If this goes ahead, perhaps I can use this usecase to battle test the IDS capabilities?

**Comment by atomczak** [comment]
Great feature @Moult!

Following our conversation, I would like to further develop this during [GSoC'21](https://github.com/opencax/GSoC/issues/45) by:
- [ ]  developing and making sure IDS checking works against new XSD (is it [this](http://standards.buildingsmart.org/IDS/ids.xsd) one?)
- [ ]  creating some IDS samples and wiki to make it easier to start for new people from AEC like myself :)
- [ ]  add the BCF output of such report (isn't it linked to [#1244](https://github.com/IfcOpenShell/IfcOpenShell/issues/1244)?)
- [ ]  add IDS authoring and integrate with BIMTester web UI - part of another [GSoC project](https://github.com/opencax/GSoC/issues/44).

My GSoC part in blue:
![GSoC IDS BCF - Frame 1](https://user-images.githubusercontent.com/22922395/114050256-6575e280-988c-11eb-9303-d1fcb04605fa.jpg)

I'm submitting the GSoC proposal, also available here: [https://docs.google.com/document/d/15oQDhYrApuHsI1Zee5bDvSqRoUz67xHMr79hdFJUoZ8/edit?usp=sharing](url)

**Comment by Moult** [comment]
Great proposal! I believe the XSD link you have is correct. I have also attached an _old_ version of the XML here.

[ids01.xml.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6283321/ids01.xml.txt)

Comparing the old with the new spec may provide some insight on the changes made formal in the XSD.

We should also organise a weekly catchup.

BTW @aothms the BCF lib uses `xmlschema` to [load the XML content and validate](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/bcf/bcf/bcfxml.py#L744) against an XSD in one go, and ships with the XSDs. I noticed with minidom validation is done manually. Any thoughts on whether it is worth switching xml libs?

**Comment by Moult** [comment]
@atomczak by the way, the webapp seems to be emerging with a Python backend, so when you get around to developing the webapp to author IDSes, if the XML generation is done server-side, then it would be ideal for it to be a Python thing too. If it is done client-side, no worries.

**Comment by Moult** [comment]
Oh, and one more thing, It would be good to investigate the ability to integrate IDS with MicroMVD's Gherkin syntax, where one would simply "call" the other. This way, it provides a nice human readable description that ties into business objectives, but the implementation still follows strict standards rather than bespoke test definitions.

**Comment by aothms** [comment]
> BTW @aothms the BCF lib uses xmlschema 

This looks really good. By the time I started there wasn't an XSD, I think it might be worth it. At the same time though there might be different dialects and versions (milestones) of IDS and the minInclusive etc aren't really part of the XSD schema, so perhaps the flexibility of using a schemaless approach might be beneficial for the time the IDS schema and implementations between vendors are still maturing.

**Comment by aothms** [comment]
> IDS and the minInclusive etc aren't really part of the XSD schema

I was just informed that the minInclusive etc, things are going to be part of the XSD schema (or maybe a second imported schema namespace). I think it's worth an experiment to see if xmlschema makes life easier.

**Comment by atomczak** [comment]
the proposal submitted ([link](https://storage.googleapis.com/summerofcode-prod.appspot.com/gsoc/core_project/doc/5467623187283968_1618247306_GSoC_Artur_Tomczak_proposal_-_IfcOpenShell_-_IDS_support.pdf?Expires=1618333720&GoogleAccessId=summerofcode-prod%40appspot.gserviceaccount.com&Signature=I21sZY3GE2rYWmOtRbxjgzhXmDcyip1WJByuHwkxjSUuci2NAgxX9PfDSD2psoYO1kPJKyW5cfXzPAl86YinM%2FHHmTBxjSKQB8PazznZBZaqK53YnWLJCBoeU2r6WX1M5l6tm884vGje17wRqKzE%2B%2F4tlOpQZcQVvOQx83VSVDB9J2p7HGQdp%2FxKlNHYWrDbQbhE0SOm5KgJK7nI7xUcvWunNYVtHVic2pIPuMWBp01RKFLsnFciOx3qBDLnCd290ajq7XNd0W5gXStHVdurzsZFa07wFA357q98qznyRU1YR40wLctMV3sD%2FoVGWdK2%2B7L7O01UBPj%2FvDminNg2Rw%3D%3D))! 

MicroMVD's, Gherkin, XML/XSD/IDS, minInclusive, web UI, IDS authoring, BCF authoring, difference between xml parsers, existing capabilities of IfcOpenShell and BIMTester... there is a lot for me to learn! I'm still confused with some of those, but looking forward to this opportunity and hope to get accepted :)

@Moult, you mentioned to schedule regular meetings, how would you like to arrange them, should all three of us meet? What's your availability? For the next couple of weeks my availability to contribute is limited due to problems around relocation to Norway and academic work, but I will at least try to work on some small aspect of it and learn. Also, which communication channel apart from videocalls do you prefer: ~~email~~, OSArch Forum, OSArch chat, this GitHub issue, GitHub Project, GitHub Wiki page for IDS sth completely else?

**Comment by Moult** [comment]
Great! There's a bit of a waiting time now until we work out how many Google slots there are. For weekly meetups and live questions, the osarch chat works best. For dev progress, this github issue works. At significant milestones , we should post on the forum so the wider community can keep track.

**Comment by atomczak** [comment]
### To-do list:

- [ ] **IDS validation:**
	- [x] Implement [xmlschema ](https://github.com/sissaschool/xmlschema/blob/a652787ae18c889940da9f6912fad36b5d688793/tests/validators/test_facets.py#L1021)for IDS.xml validation against XSD
	- [ ] Implement [xmlschema ](https://github.com/sissaschool/xmlschema/blob/a652787ae18c889940da9f6912fad36b5d688793/tests/validators/test_facets.py#L1021)for IDS parsing for the IFC validation against IDS (similar to [bcfxml.py](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/bcf/bcf/v2/bcfxml.py))
	- [ ] Implement/test all facets:
		- [ ] Entity + predefined type
		- [ ] Classification
		- [ ] Property
		- [ ] Material
	- [ ] Implement all restrictions:
		- [ ] Enumeration
		- [ ] Length
		- [ ] minLength, maxLength
		- [ ] minInclusive, maxInclusive, minExclusiv, maxExclusive
		- [ ] fractionDigits
		- [ ] totalDigits
		- [ ] whiteSpace
		- [ ] xs:patterns (~RegEx)
	- [ ] Human readable messages (sentences) to be declared outside of the code (to be able to change language or structure)
	- [ ] Schema differences, e.g. 2x3 vs 4.0 to be declared separately in a dictionary, not hardcoded. E.g [IfcClassificationReference](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcexternalreferenceresource/lexical/ifcclassificationreference.htm)
		
- [ ] **BCF export**
	- [ ] Create simple BCF test using [bcf module](https://github.com/atomczak/IfcOpenShell/tree/v0.6.0/src/bcf)
	- [ ] Add BCF export of the IDS validation
	- [ ] Add view creation
	
- [ ] **IDS authoring UI**
	- [ ] Create mockup/demo of IDS authoring + workflow
	- [ ] Create basic Flask form page for writting simple case of IDS with one entity, one applicability and one property requirement
	- [ ] Add conversion to IDS XML format
	- [ ] Add download IDS button
	- [ ] Form should be generated based on current [IDS.xsd](http://standards.buildingsmart.org/IDS/ids.xsd), releases here:  [github/buildingSMART](https://github.com/buildingSMART/IDS/tree/master/Development)
	- [ ] Add a few predefined examples/usecases of IDS
	- [ ] Add dynamic fields (flask-wtf or angular/react)
	- [ ] Add pattern (regex) validation

**Comment by atomczak** [comment]
@Moult, @aothms, 

Speaking about the message syntax, I'm not sure if it follows some guidelines, such as this Gherkin syntax or not. Currently we have for example:
> "We expect an entity name 'IfcWall' and a property 'IsExternal' in 'Pset_WallCommon' with value 'not specified' 
> #13740=IfcWall('1nZz9768j4pAFS7rcljTUA',#25,'TEST wall name',$,$,#13668,#13735,'718FD247-188B-44CC-A3DC-1F59AFB5D78A') has an entity name 'IfcWall' 
> and a property 'IsExternal' in 'Pset_WallCommon' with value 'True' so is not compliant"

which is a bit long and mixes both failing and passing sentences, sometimes confusing. Can we reduce it to:

> 'IfcWall' #13740 is not compliant, because property 'IsExternal' of 'Pset_WallCommon' has value 'True' instead of 'not specified'.

similarly for passing ones:

> 'IfcWall' of id '1nZz9768j4pAFS7rcljTUA' is compliant, because property 'IsExternal' of 'Pset_WallCommon' has value 'True' as expected.


What do you think about grouping messages together? 
>  1. IDS expects 'IfcSpace' parameter 'foo' to be equal to 'bar'.
> > 1.1 'IfcSpace' #3621 has 'foo' equal to 'baz' instead of 'bar'.
> > 1.2 'IfcSpace' #3622 has 'foo' equal to 'dar' instead of 'bar'.
>  2. IDS expects 'IfcSpace' parameter 'foo2' to be equal to 'bar'.
> > 2.1 'IfcSpace' #3621 has 'foo2' equal to 'baz' instead of 'bar'.

**Comment by atomczak** [comment]
I've found two bugs in our code that I'm trying to resolve: 
1. Currently it's only validating one requirement of a type, so if somebody wants an entity two have 2+ properties it will only validate first from the list.
2.  If there are multiple IDS defined in a single file, it treats them separately, so one entity can pass one IDS but fail the other. As a result we get in the report two opposite results and I assume ideally we would like to get one (?):
`{'guid': '1nZz9768j4pAFS7rcljTU5', 'result': True, 'sentence': "Given an instance with..."}`
`{'guid': '1nZz9768j4pAFS7rcljTU5', 'result': False, 'sentence': "Given an instance with..."}`

Added to the [**To-do list**](https://github.com/IfcOpenShell/IfcOpenShell/issues/1349#issuecomment-857534144)

**Comment by atomczak** [comment]
> 1. Currently it's only validating one requirement of a type, so if somebody wants an entity two have 2+ properties it will only validate first from the list.

My mistake when switching to xmlschema (from DOM to dictionaries). Fixed it.

**Comment by aothms** [comment]
Wonderful overview @atomczak 

> Enumeration
> Length
> minLength, maxLength
> minInclusive, maxInclusive, minExclusiv, maxExclusive
> fractionDigits
> totalDigits
> whiteSpace
> xs:patterns (~RegEx)

I don't think all of these are intended to be used in the IDS spec. Maybe @berlotti can comment?

> What do you think about grouping messages together?
> 
> > 1. IDS expects 'IfcSpace' parameter 'foo' to be equal to 'bar'.
> > 
> > > 1.1 'IfcSpace' #3621 has 'foo' equal to 'baz' instead of 'bar'.
> > > 1.2 'IfcSpace' #3622 has 'foo' equal to 'dar' instead of 'bar'.
> > 
> > 
> > 
> > 1. IDS expects 'IfcSpace' parameter 'foo2' to be equal to 'bar'.
> > 
> > > 2.1 'IfcSpace' #3621 has 'foo2' equal to 'baz' instead of 'bar'.

I think it's a good idea. It'll reduce some of the wall of text we currently have. It's a bit like a matrix transpose of the information. It probably just shows we need a better data structure for capturing the results so that this kind of grouping and sorting is easy.

**Comment by atomczak** [comment]
I listed those restrictions based on IDS.xsd:
`Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace)`

**Comment by atomczak** [comment]
Regarding the grouping of messages, currently we have a list:



code-wise I don't see any problems. The output would become a hierarchy not a list, but also benefit from less text - simpler to understand. I suggest:
```
[{'specification': 'First IDS', 
 'sentence': 'Given an instance with an entity name 'IfcWall'\nWe expect an entity name 'IfcWall' of predefined type 'CLADDING' and a property 'Codice WBS' in 'Anas' with value 'Whatever1 or TestTest or Whatever2'',
 'results': [{'guid': '1nZz9768j4pAFS7rcljTU1', 'result': False, 'sentence': "IfcWall 'TEST wall name 1' (#13740) has an entity name 'IfcWall' of predefined type 'NOTCLADDING' and a property 'Codice WBS' in 'Anas' with value 'TestTest' so is not compliant"}
             {'guid': '1nZz9768j4pAFS7rcljTU2', 'result': False, 'sentence': "IfcWall 'TEST wall name 2' (#137402) has an entity name 'IfcWall' of predefined type 'None' and no set 'Anas' so is not compliant"}]
},
{'specification': 'Second IDS', 
 'sentence': 'Given an instance with an entity name 'IfcWall'\nWe expect an entity name 'IfcWall' of predefined type 'CLADDING' and a property 'Codice WBS' in 'Anas' with value 'Whatever1 or TestTest or Whatever2'',
 'results': [{'guid': '1nZz9768j4pAFS7rcljTU1', 'result': False, 'sentence': "IfcWall 'TEST wall name 1' (#13740) has an entity name 'IfcWall' of predefined type 'NOTCLADDING' and a property 'Codice WBS' in 'Anas' with value 'TestTest' so is not compliant"}
             {'guid': '1nZz9768j4pAFS7rcljTU2', 'result': False, 'sentence': "IfcWall 'TEST wall name 2' (#137402) has an entity name 'IfcWall' of predefined type 'None' and no set 'Anas' so is not compliant"}]
}]
```
I realise it doesn't solve the initial problem: one element can be flagged multiple times, once as True, once as False. For this we could add another level of hierarchy, but I'm not sure if it's helpful 🤔 

```
[{'specification': 'First IDS', 
 'sentence': 'Given an instance with an entity name 'IfcWall'\nWe expect an entity name 'IfcWall' of predefined type 'CLADDING' and a property 'Codice WBS' in 'Anas' with value 'Whatever1 or TestTest or Whatever2'',
 'results': [{'guid': '1nZz9768j4pAFS7rcljTU1', 'result': False, 'sentence': "IfcWall 'TEST wall name 1' (#13740) has an entity name 'IfcWall' of predefined type 'NOTCLADDING' and a property 'Codice WBS' in 'Anas' with value 'TestTest' so is not compliant"}
             {'guid': '1nZz9768j4pAFS7rcljTU2', 'result': False, 'sentence': "IfcWall 'TEST wall name 2' (#137402) has an entity name 'IfcWall' of predefined type 'None' and no set 'Anas' so is not compliant"}]
},
{'specification': 'Second IDS', 
 'sentence': 'Given an instance with an entity name 'IfcWall'\nWe expect an entity name 'IfcWall' of predefined type 'CLADDING' and a property 'Codice WBS' in 'Anas' with value 'Whatever1 or TestTest or Whatever2'',
 'results': [{'guid': '1nZz9768j4pAFS7rcljTU1', 'result': False, 'sentence': "IfcWall 'TEST wall name 1' (#13740) has an entity name 'IfcWall' of predefined type 'NOTCLADDING' and a property 'Codice WBS' in 'Anas' with value 'TestTest' so is not compliant"}
             {'guid': '1nZz9768j4pAFS7rcljTU2', 'result': False, 'sentence': "IfcWall 'TEST wall name 2' (#137402) has an entity name 'IfcWall' of predefined type 'None' and no set 'Anas' so is not compliant"}]
}]
```

**Comment by atomczak** [comment]
>   * [x]  Draw the UI workflow
>   * [x]  Create mockup/demo of IDS authoring
>   * [x]  Create basic Flask form page for writting simple case of IDS with one entity, one applicability and one property requirement
>   * [x]  Add dynamic fields (flask-wtf or angular/react)

Sharing the work-in-progress authoring web-app: [http://artomczak.pythonanywhere.com/create](http://artomczak.pythonanywhere.com/create). Bare in mind it only looks like creating IDS, there is no save or validate functionality. Source-code repo: [https://github.com/atomczak/IDS-web-app](https://github.com/atomczak/IDS-web-app)

**Comment by atomczak** [comment]
> * [ ] write tests ([link](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/test))
> * [ ]  prepare and upload test IDS and IFC files ([IfcOpenShell/files](https://github.com/IfcOpenShell/files/tree/eca4a52d7c758a92bad6910fa830436a836745bf))?

basic tests written in test_ids.py using unittest module. Validate using: `Python test_ids.py` 
from the ifcopenshell location and should result in 6 successful results. More tests to be implemented on: invalid IDS, IDS authoring, IFC validation and result output.

Test files were created and can be found in this separate repo: [https://github.com/atomczak/Sample-BIM-Files/tree/main/IDS](https://github.com/atomczak/Sample-BIM-Files/tree/main/IDS)

**Comment by atomczak** [comment]
Recent development: support for the new IDS 0.4.1 schema, full restrictions support including authoring, implemented asdict() functionality for all classes to easily convert to dictionaries and IDS.xml.

**Comment by atomczak** [comment]
Should we close this issue @Moult @aothms?

**Comment by aothms** [comment]
Yes, let's do that. @atomczak but maybe first scroll through the text and see if there is something interesting we need to carry over to a new issue. After that feel free to close.

**Comment by atomczak** [comment]
I'm not able to close it. I also couldn't add labels to issues. Can you do it? I have checked the text and didn't see anything that we might still need.

**Comment by MarkusSteinbrecher** [comment]
@atomczak I have just stumbled across this discussion ... I am playing around again with Ifcopenshell and IDS and I was wondering if you took this idea any further: https://github.com/atomczak/IDS-web-app ... the repo seems to have vanished. I would be very interested in having an open source solution around IDS. Thanks!

**Comment by Moult** [comment]
@MarkusSteinbrecher there is https://blenderbim.org/ifctester which is half built.
