### ISSUE TITLE
BlenderBIM IFC Git functionality status

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#3096]
Leaving this here to keep track of Git support status.

- [x] Create and add an IFC project to a repository
- [x] Commit and retrieve revisions
- [x] Create branches
- [x] View revision history per branch, including showing tags, dates, authors and commit messages
- [x] Visualise differences between current and selected revision
- [x] A separate Git installation in user's `PATH` is required
- [x] Merging of branches if `ifcmerge` is in user's `PATH`
- [x] Documentation
- [x] Tests in test suite
- [x] Creating and removing tags brunopostle/ifc-git#2
- [x] Sorting of revision list not fully functional, ie. reverse sort is ok, but pattern matching isn't
- [x] Switching revisions is ok and not too crashy, but some parts of BlenderBIM UI are not cleared of old data (drawing sheets, type thumbnails). This functionality to clear and load an IFC project should move to `bim.ifc` or something.
- [x] brunopostle/ifc-git#6
- [x] brunopostle/ifc-git#5 clone, fetch and push need UI for managing named remotes/origins
- [ ] brunopostle/ifc-git#10 there are lots of ways a repository may not be usable
- [x] brunopostle/ifc-git#4 Visual diffs are simplistic, `git log -L` would allow us to retrieve the entire revision history of a single IFC entity. Selected object log is viewable, but entity log could also be viewable in the Debug panel
- [ ] Make revision list and most recent tag available to drawing generation
- [x] Make revised elements available for revision cloud drawing
- [x] brunopostle/ifc-git#3 `ifcmerge` could switch from merging by rewriting local step-ids to rewriting remote ids, this would be more in-line with user expectations
~Swapping from GitPython to [dulwich](https://github.com/jelmer/dulwich) would remove the requirement to install Git separately~
- [ ] #3783 committing/merging/switching etc.. only concerns itself with the current IFC project file, but users will want to put SVG files, textures, docs, stylesheets in the repository. This needs an interface for adding these files, and a toggle to include/exclude all files when commiting etc..
- [ ] default branch should be `main`. If `global init.defaultBranch` is *not* set, initialise repositories with a `main` branch

@brunoperdigao @theoryshaw You may have noticed some items I haven't listed

**Comment by brunopostle** [comment]
Some notes about a situation where a three-way merge of Native IFC branches might fail badly.

A simple failure would be where an entity or attribute has been modified in one branch and deleted/modified in another. This will fail, but it is easy to catch and inform the user that they need to resolve the problem manually. I'm not worried about this sort of thing 

An example of a nasty failure is in those places where the IFC schema is not fully normalised. ie. Elements have *ObjectPlacement* and *Representation* attributes that can reference entities that can also be referenced by other Elements.

If, for example, a Representation is used by a single Element instance, and a user deletes that instance; an over-enthusiastic Native IFC tool might decide to purge the Representation - since the Representation is now orphaned. If however, in another branch that instance is copied by the user, resulting in a second Element referencing that Representation - the result of the merge is a dangling reference to a deleted Representation and an invalid IFC model.

The obvious solution is to check the graph in the merge tool and fail with an error when the graph is broken like this (I'll do this in ifcmerge), but this still leaves the user with a failed merge.

So I'm thinking that Native IFC editors might need to be cautious about purging orphaned data when deleting stuff, as there may be other users of this data in other branches. Purging orphaned data should then be a specific operation or user interface.
